Repository GatorEducator/dockagator, pull requests merged in 2020-09, with the labels that each got.

#6 Add Pandoc
  .github/workflows/check.yml
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
  .github/workflows/validate-pr.yml
  .travis.yml
  Dockerfile
  README.md
Labels: enhancement, minor

#9 Add check for merged PR before doing release actions
  .github/workflows/release.yml
Labels: bug

#10 Fix issue with Docker action
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
  .github/workflows/validate-pr.yml
Labels: patch

#11 Add Poetry and Python 3.8.5
  Dockerfile
Labels: minor
